fix buffered update of projects with `/` in their name
`/` causes to create the log file in a subdirectory. To workaround it, just
make sure all parent directories exist before opening the file.

Error message:
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/m1cha/nbu/west/src/west/app/project.py", line 874, in _update_concurrent_thread
    logfile = open(os.path.join(logdir, project.name), "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvgyi7q1z/nanopb/nanopb'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/m1cha/nbu/west_venv/bin/west", line 33, in <module>
    sys.exit(load_entry_point('west', 'console_scripts', 'west')())
  File "/home/m1cha/nbu/west/src/west/app/main.py", line 779, in main
    app.run(argv or sys.argv[1:])
  File "/home/m1cha/nbu/west/src/west/app/main.py", line 106, in run
    self.run_command(argv)
  File "/home/m1cha/nbu/west/src/west/app/main.py", line 336, in run_command
    cmd.run(args, unknown, self.topdir, manifest=self.manifest)
  File "/home/m1cha/nbu/west/src/west/commands.py", line 140, in run
    self.do_run(args, unknown)
  File "/home/m1cha/nbu/west/src/west/app/project.py", line 819, in do_run
    self.update_all()
  File "/home/m1cha/nbu/west/src/west/app/project.py", line 985, in update_all
    (failed, updated) = self.update_project_list(projects)
  File "/home/m1cha/nbu/west/src/west/app/project.py", line 943, in update_project_list
    failed, updated = self.update_project_list_parallel(projects)
  File "/home/m1cha/nbu/west/src/west/app/project.py", line 914, in update_project_list_parallel
    for index, successful in enumerate(
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpvgyi7q1z/nanopb/nanopb'
```

Signed-off-by: Michael Zimmermann <sigmaepsilon92@gmail.com>