project: make a list from filtered project iterator
`filter` is not indexable, but the parallel update implementation requires that
it is.

Before this patch, `west update -j2 PROJECT_NAME` failed with:
TypeError: 'filter' object is not subscriptable

Signed-off-by: Michael Zimmermann <sigmaepsilon92@gmail.com>