.github: upgrade to checkout@v4 and setup-python@v5
Long overdue; both where still at @v1!

Found by chance in
https://github.com/zephyrproject-rtos/west/actions/runs/9275086435/job/25518959121?pr=711
where all macos-latest configs failed like this:
```
Run actions/setup-python@v1
Error: Version 3.8 with arch x64 not found
Available versions:
  (empty)
```

Signed-off-by: Marc Herbert <marc.herbert@intel.com>