app: print error instead of assert
if running with invalid version (for instance newer than current
west), print (more) user-friendly error such as:

FATAL ERROR: west v1.0 or later is required by the manifest
  West version: v0.8.99
  Manifest file: west/west.yml
  Please upgrade west and retry.

instead of:

  File "west/src/west/app/main.py", line 172, in handle_builtin_manifest_load_err
    assert args.command not in no_manifest_ok
AssertionError

Signed-off-by: Jacob Siverskog <jacob@teenage.engineering>