manifest: restore "path: ." ability but with a warning
Restore the ability to have a project at the top level but with an
"unsupported" warning printed every time.

Fixes v1.3 commit 2b2d3f2685e6 ("manifest: Do not allow projects inside
the west directory") which accidentally broke it with an pretty obscure
backtrace:

File "python/site-packages/west/manifest.py", line 2460, in _load_project
    if Path(ret_norm).parts[0] == util.WEST_DIR:
       ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

Fixes issue number #910

This is STILL not supported!

Signed-off-by: Marc Herbert <marc.herbert@intel.com>